spring:
  application:
    name: education-system
  profiles:
    active: simple
  
  # 简化的数据源配置
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  h2:
    console:
      enabled: true
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

# JWT配置
jwt:
  secret: mySecretKey12345678901234567890
  expiration: 86400000

# 日志配置
logging:
  level:
    com.education.system: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG