spring:
  application:
    name: education-system-test
  
  main:
    allow-circular-references: true
  
  datasource:
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
    username: postgres.vbdzzryvrsqpmdrkhvxr
    password: 180031
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# MyBatis Plus Configuration  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT Configuration (测试环境)
jwt:
  secret: testSecretKey123456789012345678901234567890
  expiration: 86400000

logging:
  level:
    com.education.system: DEBUG
    org.springframework.test: DEBUG